### Parse Simple Excel
POST http://localhost:8080/api/excel/parse
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="file"; filename="case1.xlsx"
Content-Type: application/vnd.openxmlformats-officedocument.spreadsheetml.sheet

< /Users/shivdaas/Downloads/case1new.xlsx
--boundary--