spring.application.name=Fucom-Hgra

# PostgreSQL Database
spring.datasource.url=jdbc:postgresql://localhost:5432/wastewaterrank
spring.datasource.username=shivdaas
spring.datasource.password=
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Server
server.port=8082